name: Test Discord Webhook

on:
  push:
    branches: [main]

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notify Webhook
        uses: EDUJOS/ds-webhook@v1.0.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: Teste do Discord
          description: Teste de webhook funcionando.